language: python
python: 2.7
env:
  - PLONE_VERSION=4.2
  - PLONE_VERSION=4.3
  - PLONE_VERSION=5.0
matrix:
  include:
    - python: 2.6
      env: PLONE_VERSION=4.0
    - python: 2.6
      env: PLONE_VERSION=4.1
  allow_failures:
    - python: 2.6
      env: PLONE_VERSION=4.0
install:
  - sed -ie "s#travis-4.x.cfg#travis-$PLONE_VERSION.x.cfg#" travis.cfg
  - mkdir -p buildout-cache/downloads
  - python bootstrap.py -c travis.cfg annotate
  - virtualenv .
  - export SETUPTOOLS_SPEC=`python bootstrap.py -c travis.cfg annotate | grep 'setuptools= ' | sed 's/= /==/'`
  - export BUILDOUT_SPEC=`python bootstrap.py -c travis.cfg annotate | grep 'zc.buildout= ' | sed 's/= /==/'`
  - bin/pip install --upgrade pip SETUPTOOLS_SPEC BUILDOUT_SPEC
  - bin/buildout -qNc travis.cfg
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - firefox -v
script: bin/test
