language: python
python: 2.7
sudo: false
cache:
  pip: true
  directories:
    - eggs
    - downloads
env:
  - PLONE_VERSION=4.3
  - PLONE_VERSION=5.0
  - PLONE_VERSION=5.1
install:
  - sed -ie "s#travis-5.x.cfg#travis-$PLONE_VERSION.x.cfg#" travis.cfg
  - pip install -r requirements.txt
  - buildout -Nc travis.cfg buildout:download-cache=downloads annotate | tee annotate.txt | grep -E 'setuptools= |zc.buildout= ' | sed 's/= /==/' > requirements.txt
  - cat annotate.txt
  - cat requirements.txt
  - pip install --upgrade -r requirements.txt
  - buildout -qNc travis.cfg buildout:download-cache=downloads
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - firefox -v
script: bin/test
