language: python
python: 2.7
sudo: false
cache:
  pip: true
  directories:
    - $HOME/buildout-cache
env:
  - PLONE_VERSION=4.2
  - PLONE_VERSION=4.3
  - PLONE_VERSION=5.0
matrix:
  include:
    - python: 2.6
      env: PLONE_VERSION=4.0
    - python: 2.6
      env: PLONE_VERSION=4.1
  allow_failures:
    - python: 2.6
      env: PLONE_VERSION=4.0
install:
  - sed -ie "s#travis-5.x.cfg#travis-$PLONE_VERSION.x.cfg#" travis.cfg
  - mkdir -p buildout-cache/{eggs,downloads}
  - virtualenv .
  - bin/pip install --upgrade pip zc.buildout
  - bin/buildout -c travis.cfg annotate | tee annotate.txt | grep -E 'setuptools= |zc.buildout= ' | sed 's/= /==/' > requirements.txt
  - cat annotate.txt
  - cat requirements.txt
  - bin/pip install --upgrade -r requirements.txt
  - bin/buildout -qNc travis.cfg
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - firefox -v
script: bin/test
